[[redirects]]
from = "/APIAddress/*"
to="http://api.vworld.kr/req/address/:splat"
status=200
force = true

[[redirects]]
from = "/itemSearch/*"
to="http://www.aladin.co.kr/ttb/api/ItemSearch.aspx/:splat"
status=200
force = true


[[redirects]]
from = "/"
to = "/index.html"
status = 200